from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from llama_manager.config import RemoteManagerConfig
from llama_manager.log_buffer import LogBuffer

if TYPE_CHECKING:
    from llama_manager.llama_client import LlamaClient
    from llama_manager.manager.backends import LocalManagedModel, RemoteModelProxy, RemoteUnmanagedModel

type ModelSUID = str


class RemoteClient(Protocol):
    def get_config(self) -> RemoteManagerConfig: ...
    async def request_slots(self, suid: str) -> list[dict]: ...
    async def request_health(self, suid: str) -> dict | None: ...
    async def send_command(self, suid: str, cmd: str) -> None: ...


class LlamaManagerProtocol(Protocol):
    def get_manager_id(self) -> str: ...
    def get_local_models(self) -> dict[ModelSUID, LocalManagedModel]: ...
    def get_remote_models(self) -> list[RemoteModelProxy]: ...
    def get_remote_unmanaged(self) -> dict[ModelSUID, RemoteUnmanagedModel]: ...
    def get_client(self, model_suid: ModelSUID) -> LlamaClient | None: ...
    def get_client_at(self, base_url: str) -> LlamaClient: ...


class Backend(Protocol):
    def get_manager_id(self) -> str: ...
    def get_suid(self) -> str: ...
    def get_name(self) -> str | None: ...
    def get_base_url(self) -> str: ...
    def get_model_ids(self) -> list[str]: ...
    def map_model_id(self, model_id: str | None) -> str | None: ...
    def is_available(self) -> bool: ...
    def get_status(self) -> dict: ...
    async def get_slots(self) -> list[dict] | None: ...
    async def get_health(self) -> dict: ...


class ManagedBackend(Backend, Protocol):
    def get_log_buffer(self) -> LogBuffer: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def restart(self) -> None: ...
