from __future__ import annotations

from typing import Protocol

from llama_manager.config import RemoteManagerConfig
from llama_manager.log_buffer import LogBuffer


class RemoteClient(Protocol):
    def get_config(self) -> RemoteManagerConfig: ...
    async def request_slots(self, remote_model_index: int) -> list[dict]: ...
    async def request_health(self, remote_model_index: int) -> dict | None: ...
    async def send_command(self, remote_model_index: int, cmd: str) -> None: ...


class Backend(Protocol):
    def get_suid(self) -> str: ...
    def get_name(self) -> str | None: ...
    def get_base_url(self) -> str: ...
    def get_model_ids(self) -> list[str]: ...
    def is_available(self) -> bool: ...
    async def get_slots(self) -> list[dict] | None: ...
    async def get_health(self) -> dict: ...


class ManagedBackend(Backend, Protocol):
    def get_log_buffer(self) -> LogBuffer: ...
    def get_status(self) -> dict: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def restart(self) -> None: ...
